// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {FairLpMath} from "../src/libraries/FairLpMath.sol";
import {TickMath} from "../src/libraries/TickMath.sol";

/// Differential test: FairLpMath.sol MUST match reference/fair_lp_value_golden.py bit-for-bit
/// across every vector in test/vectors/fair_lp.json (generated by reference/gen_vectors.py).
/// This is the funds-critical KERNEL's correctness gate — a single mismatched wei fails the build.
contract FairLpMathDiffTest is Test {
    struct V {
        uint256[] liquidity;
        int256[]  tickLower;
        int256[]  tickUpper;
        uint256[] sqrtFair;
        uint256[] price0;
        uint256[] price1;
        uint256[] dec0;
        uint256[] dec1;
        uint256[] priceLoan;
        uint256[] loanDec;
        uint256[] totalLoan;
        uint256[] expA0;
        uint256[] expA1;
        uint256[] expValue;
        uint256[] expValueLoan;
        uint256[] expZap;
        uint256   n;
    }

    V v;

    function setUp() public {
        string memory json = vm.readFile("test/vectors/fair_lp.json");
        v.liquidity = vm.parseJsonUintArray(json, ".liquidity");
        v.tickLower = vm.parseJsonIntArray(json, ".tickLower");
        v.tickUpper = vm.parseJsonIntArray(json, ".tickUpper");
        v.sqrtFair  = vm.parseJsonUintArray(json, ".sqrtFair");
        v.price0    = vm.parseJsonUintArray(json, ".price0");
        v.price1    = vm.parseJsonUintArray(json, ".price1");
        v.dec0      = vm.parseJsonUintArray(json, ".dec0");
        v.dec1      = vm.parseJsonUintArray(json, ".dec1");
        v.priceLoan = vm.parseJsonUintArray(json, ".priceLoan");
        v.loanDec   = vm.parseJsonUintArray(json, ".loanDec");
        v.totalLoan = vm.parseJsonUintArray(json, ".totalLoan");
        v.expA0     = vm.parseJsonUintArray(json, ".expA0");
        v.expA1     = vm.parseJsonUintArray(json, ".expA1");
        v.expValue  = vm.parseJsonUintArray(json, ".expValue");
        v.expValueLoan = vm.parseJsonUintArray(json, ".expValueLoan");
        v.expZap    = vm.parseJsonUintArray(json, ".expZap");
        v.n         = vm.parseJsonUint(json, ".n");
    }

    function test_differential_against_golden() public view {
        assertGt(v.n, 0, "no vectors loaded");
        for (uint256 i = 0; i < v.n; i++) {
            (uint256 value, uint256 a0, uint256 a1) = FairLpMath.fairValue(
                uint128(v.liquidity[i]),
                int24(v.tickLower[i]),
                int24(v.tickUpper[i]),
                uint160(v.sqrtFair[i]),
                v.price0[i],
                v.price1[i],
                uint8(v.dec0[i]),
                uint8(v.dec1[i])
            );
            assertEq(a0, v.expA0[i], string.concat("a0 mismatch @", vm.toString(i)));
            assertEq(a1, v.expA1[i], string.concat("a1 mismatch @", vm.toString(i)));
            assertEq(value, v.expValue[i], string.concat("value mismatch @", vm.toString(i)));

            // loan-unit valuation (health/liquidation input) must also match golden bit-for-bit
            (uint256 vLoan,,) = FairLpMath.fairValueInLoan(
                uint128(v.liquidity[i]), int24(v.tickLower[i]), int24(v.tickUpper[i]), uint160(v.sqrtFair[i]),
                v.price0[i], v.price1[i], v.priceLoan[i], uint8(v.dec0[i]), uint8(v.dec1[i]), uint8(v.loanDec[i])
            );
            assertEq(vLoan, v.expValueLoan[i], string.concat("valueLoan mismatch @", vm.toString(i)));

            // open-time zap split must match golden bit-for-bit
            uint256 zap = FairLpMath.zapSwapAmountToToken0(
                v.totalLoan[i], int24(v.tickLower[i]), int24(v.tickUpper[i]), uint160(v.sqrtFair[i]),
                v.price0[i], v.price1[i], uint8(v.dec0[i]), uint8(v.dec1[i])
            );
            assertEq(zap, v.expZap[i], string.concat("zap mismatch @", vm.toString(i)));
        }
    }

    function test_zapRatio_nearMaxTick_usesHighResolution() public pure {
        uint256 got = FairLpMath.zapSwapAmountToToken0(
            1e18,
            887100,
            887220,
            TickMath.getSqrtRatioAtTick(887160),
            336467360688469975974708440897698435998,
            1,
            0,
            0
        );

        assertEq(got, 499999999999999995);
    }

    function test_zapRatio_nearMinTick_usesHighResolution() public pure {
        uint256 got = FairLpMath.zapSwapAmountToToken0(
            1e18,
            -887220,
            -887100,
            TickMath.getSqrtRatioAtTick(-887160),
            1,
            336467360574169773077979175576983095605,
            0,
            0
        );

        assertEq(got, 499999992869256612);
    }

    function test_zapRatio_precisionInsufficient_revertsDistinctly() public {
        vm.expectRevert(bytes4(keccak256("ZapRatioPrecisionInsufficient()")));
        this.zapRatioPrecisionProbe();
    }

    function zapRatioPrecisionProbe() external pure returns (uint256) {
        return FairLpMath.zapSwapAmountToToken0(
            1e18, -1, 1, TickMath.getSqrtRatioAtTick(0), 1, 1, 77, 77
        );
    }

    function test_zapRatio_legalZero_remainsZero() public pure {
        uint256 got = FairLpMath.zapSwapAmountToToken0(
            1e18, -100, 100, TickMath.getSqrtRatioAtTick(100), 1, 1, 0, 0
        );

        assertEq(got, 0);
    }

    function test_zapRatio_currentWethUsdg_bitExact() public pure {
        uint256 got = FairLpMath.zapSwapAmountToToken0(
            1000e6,
            -192780,
            -191580,
            5314786713428871308883051,
            4500e8,
            1e8,
            18,
            6
        );

        assertEq(got, 517644551);
    }

    // Independent rational continuous solutions (no amount/value floors), computed
    // from Q96*(B-P)/(P*B)*price0/scale0 and (P-A)/Q96*price1/scale1.
    function test_zapRatio_nonzeroAmountRounding_recoversContinuousRatio() public pure {
        (uint256 a0, uint256 a1) = FairLpMath.fairAmounts(
            1e18, 700000, 700120, TickMath.getSqrtRatioAtTick(700050)
        );
        assertEq(a0, 2);
        assertGt(a1, 0);
        uint256 got = FairLpMath.zapSwapAmountToToken0(
            1e18, 700000, 700120, TickMath.getSqrtRatioAtTick(700050), 1e30, 1, 0, 0
        );
        assertEq(got, 357099691130708442, "nonzero amount rounding distorts ratio");
    }

    function test_zapRatio_nonzeroValueRounding_recoversContinuousRatio() public pure {
        (uint256 a0, uint256 a1) = FairLpMath.fairAmounts(1e18, -60, 120, uint160(1 << 96));
        assertEq(a0 / 1e15, 5);
        assertEq(a1 / 1e15, 2);
        uint256 got = FairLpMath.zapSwapAmountToToken0(
            1e18, -60, 120, uint160(1 << 96), 1, 1, 15, 15
        );
        assertEq(got, 666333516815323819, "nonzero value rounding distorts ratio");
    }

    function test_zapRatio_nonzeroMaxReferenceStillImprecise_reverts() public {
        vm.expectRevert(FairLpMath.ZapRatioPrecisionInsufficient.selector);
        this.zapNonzeroMaxPrecisionProbe();
    }

    function zapNonzeroMaxPrecisionProbe() external pure returns (uint256) {
        return FairLpMath.zapSwapAmountToToken0(1e18, -1, 2, uint160(1 << 96), 1, 1, 34, 34);
    }

}
